
package org.soa.ws.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SocialMediaInfosImplService", targetNamespace = "http://test.ws.soa.org/", wsdlLocation = "http://hedia:8080/SocialMediaInfosWS/SocialMediaInfosImplService?wsdl")
public class SocialMediaInfosImplService
    extends Service
{

    private final static URL SOCIALMEDIAINFOSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOCIALMEDIAINFOSIMPLSERVICE_EXCEPTION;
    private final static QName SOCIALMEDIAINFOSIMPLSERVICE_QNAME = new QName("http://test.ws.soa.org/", "SocialMediaInfosImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://hedia:8080/SocialMediaInfosWS/SocialMediaInfosImplService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOCIALMEDIAINFOSIMPLSERVICE_WSDL_LOCATION = url;
        SOCIALMEDIAINFOSIMPLSERVICE_EXCEPTION = e;
    }

    public SocialMediaInfosImplService() {
        super(__getWsdlLocation(), SOCIALMEDIAINFOSIMPLSERVICE_QNAME);
    }

    public SocialMediaInfosImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOCIALMEDIAINFOSIMPLSERVICE_QNAME, features);
    }

    public SocialMediaInfosImplService(URL wsdlLocation) {
        super(wsdlLocation, SOCIALMEDIAINFOSIMPLSERVICE_QNAME);
    }

    public SocialMediaInfosImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOCIALMEDIAINFOSIMPLSERVICE_QNAME, features);
    }

    public SocialMediaInfosImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SocialMediaInfosImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SocialMediaInfos
     */
    @WebEndpoint(name = "SocialMediaInfosImplPort")
    public SocialMediaInfos getSocialMediaInfosImplPort() {
        return super.getPort(new QName("http://test.ws.soa.org/", "SocialMediaInfosImplPort"), SocialMediaInfos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SocialMediaInfos
     */
    @WebEndpoint(name = "SocialMediaInfosImplPort")
    public SocialMediaInfos getSocialMediaInfosImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://test.ws.soa.org/", "SocialMediaInfosImplPort"), SocialMediaInfos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOCIALMEDIAINFOSIMPLSERVICE_EXCEPTION!= null) {
            throw SOCIALMEDIAINFOSIMPLSERVICE_EXCEPTION;
        }
        return SOCIALMEDIAINFOSIMPLSERVICE_WSDL_LOCATION;
    }

}
